config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root to: 'pages#homepage'

    get '/about' => 'pages#about'
    get '/research' => 'pages#research'
    get '/speedcubing' => 'pages#speedcubing'

    get '/contact' => 'messages#new'
    post '/contact' => 'messages#create', as: 'create_message'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new message_params
    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      redirect_to contact_path
      flash[:success] = t('.succesful_submission')
    else
      render :new
    end
  end

  private
  def message_params
    params.require(:message).permit(:name, :email, :subject, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end

  def about
  end

  def research
  end

  def speedcubing
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = "")
    base_title = "Alberto Pérez de Rada Fiol"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      danger: "alert-danger",
      warning: "alert-warning",
      info: "alert-info",

      recaptcha_error: "alert-danger",
    }[flash_type.to_sym] || flash_type.to_s
  end

  def fa_icon(id)
    content_tag :i, "", class: "fa fa-#{id}"
  end
end

app/views/layouts/_flash.html.erb
<div id="flash-alerts" class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert <%= bootstrap_class_for message_type %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-2 text-center">
        <div class="service-box">
          <%= link_to fa_icon("facebook"), "https://www.facebook.com/alberto.perezderada", class: "fa-4x wow bounceIn page-scroll", target: "_blank" %>
        </div>
      </div>
      <div class="col-sm-2 text-center">
        <div class="service-box">
          <%= link_to fa_icon("twitter"), "https://twitter.com/APdRF1", class: "fa-4x wow bounceIn page-scroll", target: "_blank" %>
        </div>
      </div>
      <div class="col-sm-2 text-center">
        <div class="service-box">
          <%= link_to fa_icon("instagram"), "https://www.instagram.com/apdrf1", class: "fa-4x wow bounceIn page-scroll", target: "_blank" %>
        </div>
      </div>
      <div class="col-sm-2 text-center">
        <div class="service-box">
          <%= link_to fa_icon("youtube-play"), "https://www.youtube.com/user/APdRF1", class: "fa-4x wow bounceIn page-scroll", target: "_blank" %>
        </div>
      </div>
      <div class="col-sm-2 text-center">
        <div class="service-box">
          <%= link_to fa_icon("github"), "https://github.com/AlbertoPdRF", class: "fa-4x wow bounceIn page-scroll", target: "_blank" %>
        </div>
      </div>
      <div class="col-sm-2 text-center">
        <div class="service-box">
          <%= link_to fa_icon("linkedin"), "https://www.linkedin.com/in/apdrf", class: "fa-4x wow bounceIn page-scroll", target: "_blank" %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <i class="fa fa-copyright"> <%= Time.new.year %> <%= t('.copyright') %></i>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('.branding'), root_path, class: "navbar-brand page-scroll" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to t('.about'), about_path, class: "page-scroll" %>
        </li>
        <li>
          <%= link_to t('.research'), research_path, class: "page-scroll" %>
        </li>
        <li>
          <%= link_to t('.speedcubing'), speedcubing_path, class: "page-scroll" %>
        </li>
        <li>
          <%= link_to t('.contact'), contact_path, class: "page-scroll" %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle top-nav" data-toggle="dropdown" data-hover="dropdown">
            <% active_locale_info = Locales::AVAILABLE[I18n.locale] %>
            <%= image_tag "flags/#{active_locale_info[:flag_id]}.png" %> <span class="hidden-sm"> <%= active_locale_info[:name] %></span>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% Locales::AVAILABLE.each do |l, data| %>
              <li>
                <%= link_to url_for( :locale => l ) do %>
                  <%= image_tag "flags/#{data[:flag_id]}.png" %> <%= data[:name] %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Alberto Pérez de Rada Fiol">
    <meta name="og:image" content='<%= asset_url("/og-header.png") %>'/>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <title><%= page_title(yield(:title)) %></title>

    <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
    <%= javascript_include_tag 'creative/manifest.js' %>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/new.html.erb
<% provide(:title, t('.title')) %>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="text-center">
        <h2 class="section-heading"><%= t('.title') %></h2>
        <hr class="light">
        <div class="contact-form" id="contact-form">
          <%= form_for @message, url: create_message_url do |f| %>

            <% if @message.errors.any? %>
              <div class="form-errors" id="form-errors">
                <p><%= t('.error') %></p>
                <ul>
                  <% @message.errors.full_messages.each do |m| %>
                    <li><%= m %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <%= f.label :name, t('.name') %>
            <%= f.text_field :name, placeholder: t('.name') %>

            <%= f.label :email, t('.email') %>
            <%= f.text_field :email, placeholder: t('.email') %>

            <%= f.label :subject, t('.subject') %>
            <%= f.text_field :subject, placeholder: t('.subject') %>

            <%= f.label :body, t('.body') %>
            <%= f.text_area :body, placeholder: t('.body') %>

            <%= f.submit t('.submit'), class: "btn btn-default btn-xl" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/about.html.erb
<% provide(:title, t('.title')) %>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading"><%= t('.title') %></h2>
        <hr class="light">
      </div>
    </div>
  </div>
</section>

<section class="photo-left">
  <div class="container">
    <div class="row">
      <%= image_tag asset_url("/images/about/me.jpg") %>
      <h3 class="sub-section-heading"><%= t('.introduction_title') %></h3>
      <p><%= t('.introduction_p1_html') %></p>
      <p><%= t('.introduction_p2') %></p>
    </div>
  </div>
</section>

<section class="bg-dark photo-right">
  <div class="container">
    <div class="row">
      <%= image_tag asset_url("/images/about/physics.jpg") %>
      <h3 class="sub-section-heading"><%= t('.physics_title') %></h3>
      <p><%= t('.physics_p1') %></p>
      <p><%= t('.physics_p2_html') %></p>
      <p><%= t('.physics_p3') %></p>
      <p><%= link_to t('.research_link'), research_path, class: "btn btn-primary btn-xl" %></p>
    </div>
  </div>
</section>

<section class="photo-left">
  <div class="container">
    <div class="row">
      <%= image_tag asset_url("/images/about/speedcubing.jpg") %>
      <h3 class="sub-section-heading"><%= t('.speedcubing_title') %></h3>
      <p><%= t('.speedcubing_p1_html') %></p>
      <p><%= t('.speedcubing_p2_html') %></p>
      <p><%= t('.speedcubing_p3') %></p>
      <p><%= link_to t('.speedcubing_link'), speedcubing_path, class: "btn btn-primary btn-xl" %></p>
    </div>
  </div>
</section>

<section class="bg-primary photo-right">
  <div class="container">
    <div class="row">
      <%= image_tag asset_url("/images/about/optimist.jpg") %>
      <h3 class="sub-section-heading"><%= t('.activities_title') %></h3>
      <p><%= t('.activities_p1') %></p>
      <p><%= t('.activities_p2') %></p>
      <p><%= t('.activities_p3') %></p>
    </div>
  </div>
</section>

app/views/pages/homepage.html.erb
<% provide(:title, t('.title')) %>

<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1><%= t('.welcome') %></h1>
      <hr>
      <p><%= t('.introduction') %></p>
    </div>
  </div>
</header>

app/views/pages/research.html.erb
<% provide(:title, t('.title')) %>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading"><%= t('pages.wip.disclaimer') %></h2>
        <hr class="light">
        <p class="text-faded"><%= t('pages.wip.information') %></p>
        <a href='<%= asset_url("/cv/[CV-#{I18n.locale.upcase}]APdRF.pdf") %>' class="btn btn-default btn-xl"><%= t('pages.wip.cv') %></a>
      </div>
    </div>
  </div>
</section>

app/views/pages/speedcubing.html.erb
<% provide(:title, t('.title')) %>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading"><%= t('pages.wip.disclaimer') %></h2>
        <hr class="light">
        <p class="text-faded"><%= t('pages.wip.information') %></p>
        <a href='<%= asset_url("/cv/[CV-#{I18n.locale.upcase}]APdRF.pdf") %>' class="btn btn-default btn-xl"><%= t('pages.wip.cv') %></a>
      </div>
    </div>
  </div>
</section>